<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>idempiere.extensions</groupId>
		<artifactId>idempiere.extension.parent</artifactId>
		<version>${revision}</version>
		<relativePath>../idempiere-extension-parent/pom.xml</relativePath>
	</parent>

	<artifactId>org.idempiere.myappx.plugin.odt.main</artifactId>
	<packaging>pom</packaging>
	<name>MyAppx Plugin : ODT Main</name>

	<modules>
		<module>org.idempiere.myappx.plugin.odt</module>
		<module>org.idempiere.myappx.plugin.odt.p2</module>
	</modules>
</project>
